version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps: 
      - checkout
      - restore_cache:
          keys:
            - bundle-v1-{{ checksum "Gemfile.lock" }}
            - bundle-v1-
      - run: 
          name: Bunlde install
          command: bundle check || bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ./
          paths:
            - vendor/bundle
  test:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          BUNDLE_PATH: vendor/bundle
    steps: 
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: RSpec
          command: |
            bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
          - build
